name: mawy_dashboard
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  badges: ^3.1.2
  flutter:
    sdk: flutter
  flutter_bounce: ^1.1.0
  flutter_expanded_tile: ^0.4.0
  flutter_hooks: ^0.21.2
  flutter_riverpod: ^2.6.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  hooks_riverpod: ^2.6.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  syncfusion_flutter_charts: ^28.2.11
  talker_flutter: ^4.6.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  hive_ce_generator: ^1.8.2
  json_serializable: ^6.9.4

flutter:
  uses-material-design: true
