// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mawy_dashboard/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AllKeysAdapter());
    registerAdapter(AuthCheckAdapter());
    registerAdapter(LoginsAdapter());
    registerAdapter(NewsIdAdapter());
  }
}
